# yaml-language-server: $schema=https://raw.githubusercontent.com/googleforgames/agones/refs/heads/release-1.54.0/examples/fleet.yaml
apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: rps-game
spec:
  replicas: 10
  template:
    spec:
      ports:
        - name: default
          containerPort: 3000
          protocol: TCP
      template:
        metadata:
          labels:
            app: rps-game
        spec:
          containers:
            - name: rps-game
              image: ghcr.io/noetarbouriech/agones-rps-game/game
