apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmaking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchmaking
  template:
    metadata:
      labels:
        app: matchmaking
    spec:
      serviceAccountName: matchmaking-sa
      containers:
        - name: matchmaking
          image: ghcr.io/noetarbouriech/agones-rps-game/matchmaking
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: matchmaking
spec:
  selector:
    app: matchmaking
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: matchmaking-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gameserverallocator
  namespace: default
rules:
  - apiGroups: ["allocation.agones.dev"]
    resources: ["gameserverallocations"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gameserverallocator-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: matchmaking-sa
    namespace: default
roleRef:
  kind: Role
  name: gameserverallocator
  apiGroup: rbac.authorization.k8s.io
